# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('code', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'farm',
                'verbose_name_plural': 'farms',
                'db_table': 'farms',
            },
        ),
    ]
